services:
  db:
    image: postgres:16-alpine
    container_name: my_wallet_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fire
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_wallet_backend
    restart: always
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/fire?sslmode=disable
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: my_wallet_frontend
    ports:
      - "5173:5173"
    volumes:
      # Mount the source code from the host to the container for hot-reloading
      - ./frontend:/app
      # This prevents the node_modules directory on the host from overwriting
      # the one installed in the container.
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_wallet_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres-data:
  pgadmin-data: